# Connection: leaf-02--vpc-loopback
# Normalized by Hedgehog NetBox Plugin
# Generated: 2025-08-06 10:42:27 UTC
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: leaf-02--vpc-loopback
  annotations:
    hnp.githedgehog.com/managed-by: hedgehog-netbox-plugin
    hnp.githedgehog.com/fabric: FGD Sync Validation Fabric
    hnp.githedgehog.com/original-file: prepop.yaml
    hnp.githedgehog.com/original-document-index: '22'
    hnp.githedgehog.com/ingested-at: '2025-08-06T10:42:27.624235+00:00'
    hnp.githedgehog.com/ingestion-version: '1.0'
spec:
  vpcLoopback:
    links:
    - switch1:
        port: leaf-02/E1/13
      switch2:
        port: leaf-02/E1/14
    - switch1:
        port: leaf-02/E1/15
      switch2:
        port: leaf-02/E1/16
